### ISSUE TITLE
LAN party interest check

### ISSUE THREAD

**Issue by garlic-hub** [SaddlebackCSS/LAN-Party#1]
Hey guys.
This is an interest check for the LAN Party. It will probably happen over spring break. Ideas for games are Warcraft 3, diablo, a mini hearthstone tournament, super smash bros (maybe a mini tournament as well), minecraft, or whatever game that enough people want to play. Comment here if you're interested with your name, game you'd like to play, and if you have a place it can be hosted. @SaddlebackCSS/owners @SaddlebackCSS/officialmembers

**Comment by Xannada** [comment]
I'm done if its towards the end of spring break

**Comment by TheFirstLairron** [comment]
I'm up for it whenever, as long as it's not a middle of the day thing.

**Comment by ozyx** [comment]
i'm down as long as it's not on the 19th

**Comment by DayWalkerr** [comment]
I am down when ever differently.

**Comment by djreisch** [comment]
I'm down for anything! My laptop isn't all that great so if we have to use our own computers it can't handle much more then League

-Daniel

**Comment by sillycupid** [comment]
Alex Liboon: woukd love to watch any games. Still working on my pc build. I can make it if it's towards the end of the spring break.

**Comment by DayWalkerr** [comment]
I'm down for some nerd gaming action. Let me know so I can get off work. 

-Bender, Chadd.

**Comment by ghost** [comment]
I'll go, can't wait. I'd love to play CS:GO or Warcraft.

**Comment by Autofire** [comment]
Sounds like fun! I might be able, maybe? Depends on the time of day. My experience is more with SSB and Hearthstone, but I'd be willing to pick up whatever you guys have.

Would we be expected to bring our own laptops? Any ideas on where it would be held yet?

**Comment by karlronsaria** [comment]
I'm in.

**Comment by OneEcho** [comment]
I'm interested.

**Comment by TheFirstLairron** [comment]
It's looking like I'm not gonna be able to go if it is at the time discussed in club. Prior family obligations that I can't blow off. Let me know if anything changes though.

**Comment by DayWalkerr** [comment]
What time and where would the LAN party be taking place?
