### ISSUE TITLE
Interest check with names

### ISSUE THREAD

**Issue by garlic-hub** [SaddlebackCSS/LAN-Party#2]
Currently I have these people listed:
- Canyon
- Andrew
- Sean
- Chris
- Zach (maybe?)
- Oz
- Jesse
- Anthony
- Krystine
- Parker
- Alex
- Dmitry
- Daniel
- Adrian

If I don't have you here, comment with your name, or if you shouldn't be here, comment and i'll take you off. Also does anyone have a projector we can use to play big screen smash bros?

**Comment by DayWalkerr** [comment]
Hey Chadd and Alexandria would love to join if we knew the time and place.

**Comment by djreisch** [comment]
I'd like my name added.

Daniel Reisch

**Comment by Stormbiter** [comment]
i (Adrian) would like to go if i knew time and place.

**Comment by garlic-hub** [comment]
@djreisch Added to list

**Comment by garlic-hub** [comment]
@Stormbiter @DayWalkerr It'll be at place in san juan capistrano on thursday at 4:30

**Comment by dragon0** [comment]
I have a projector, but it's not high resolution  (1024 x 768 I think). I'll bring it if no one else has one. 

-------- Original message --------

**Comment by garlic-hub** [comment]
@dragon0 Does it support hdmi?

**Comment by Stormbiter** [comment]
@slimchahla do you have an address i can use

**Comment by garlic-hub** [comment]
@Stormbiter If you didnt get my number during cs club, shoot me an email with your number farid.chahla@gmail.com and ill text you it

**Comment by Stormbiter** [comment]
@slimchahla i have sent you an email with my number

**Comment by dragon0** [comment]
No, it's VGA. I though I had an HDMI->VGA adapter (actually, I /know/ I 
got one for my Raspberry Pi) but I can't find it. I'll keep looking, but 
if someone else has one and can bring it, that'd be great.
