### ISSUE TITLE
LAN Party 2.0

### ISSUE THREAD

**Issue by garlic-hub** [SaddlebackCSS/LAN-Party#5]
Hey guys. Just like before but this time we'll have enough tables and the internet wont give us the finger for 2 hours. Potluck so bring food. I'd appreciate if you could comment here WITH YOUR NAME or shoot me a text if you're coming. It will be on May 25 @ 4:30PM. My number is 949-374-2064. Text/call me if you need the address. Ass will be whooped if it gets on /b/
@SaddlebackCSS/officialmembers

**Comment by ghost** [comment]
----- Dmitry ----- 
Good times and dank memes are short ahead.

**Comment by dragon0** [comment]
Sean here. Will be there.

**Comment by simpleskater123** [comment]
This is in regard to the message that was sent to me by means of internet. I will be making an appearance at your place of residence! Please instruct me on what you would like me to bring as far as delicacies. Respectfully Submitted,

 Cole Eastlund 

```
On Thursday, April 28, 2016 10:05 PM, Raven <notifications@github.com> wrote:
```

 Sean here. Will be there.

**Comment by Krystine** [comment]
I'LL BE THERE 🙌🏻💻⌨🕹💾🖥🌈☄🌲👏🏻🤓😁☕️🌌💜

**Comment by ozyx** [comment]
I b there mon

**Comment by rpadilla6** [comment]
Ryan Padilla, I'll be there.

**Comment by DayWalkerr** [comment]
Hey Chadd and Alexandria will be there for sure. Do i need to bring a table
this time?

**Comment by OneEcho** [comment]
I'll be there again
