### ISSUE TITLE
LAN Party 2.0 list

### ISSUE THREAD

**Issue by garlic-hub** [SaddlebackCSS/LAN-Party#6]
Hey guys. I hope your finals aren't cucking you. So we have more people coming this time with a few not sures. Currently I have these people listed:
- Dmitry @o5akafeeva 
- Sean @dragon0 
- Jesse @ozyx 
- Kirstyn @kierstynnnn 
- Cole @simpleskater123 
- Krystine @Krystine 
- Anthony @anthonykoutroulis 
- Ryan @rpadilla6 
- Chad @DayWalkerr 
- Alex
- Canyon @Canyonschwartz 
- Oz @theozornelas 
- Ramin 
- Chris @rezatnoMsirhC 
- Katie @misslame 
- Andrew @DoctorDendrite 
- Parker @Xannada 
- Lance @Lance-Orgill 
- Drew 
- Edgar @Sorevitno
- Adrian

That's a total of 21 including me. We're definitely going to need more tables. And food. 
So if you could, bring some tables and a snack for people. LAN party will be Wed, May 25 at 4:30. Message me or comment if the list doesn't look right to you

**Comment by garlic-hub** [comment]
@SaddlebackCSS/officialmembers

**Comment by DayWalkerr** [comment]
i can bring a table or two. and some chairs.

**Comment by chadrt21** [comment]
I can come to. Is there anything other than food and fun that I need to bring? And where are we meeting again?

**Comment by garlic-hub** [comment]
@cross21 Hey chad. Call or text me at 949-374-2064 and I'll give you the address
